### ISSUE TITLE
Client-server on two different machines

### ISSUE THREAD

**Issue by rinki19045083** [nkh-lab/genivi-capi-someip-examples#4]
Hi,

I am completely new to commonAPI someip, have some prior understanding of vsomeip. I need to build the server and client on two different machines. could you pls explain How can i do that. what would the file structure and json file configuration. what would be the client app name in .cpp file which need to give in vsomeip json file also.

**Comment by nkh-lab** [comment]
This section is for issues, please use it properly. Closed because it is not a issue.
